FROM python:3.8
# Используем официальный образ Python как базовый
FROM python:3.8-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем содержимое текущей директории в контейнер
COPY . /app

# Устанавливаем Flask
RUN pip install flask

# Открываем порт 8000
EXPOSE 8000

# Запускаем приложение
CMD ["python", "app.py"]
