experimentName: RandomForest_WineQuality_Optimization
searchSpace:
  n_estimators:
    _type: choice
    _value: [50, 100, 150, 200]
  max_depth:
    _type: choice
    _value: [None, 10, 20, 30]
trialCommand: python 5.py
trialCodeDirectory: .
trialGpuNumber: 0
trialConcurrency: 2
maxExperimentDuration: 24h
maxTrialNumber: 100
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  useActiveGpu: True