apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: bone-fracture-ensemble
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 3
    tensorflow:
      serviceType: ClusterIP
      protocol: grpc
    containers:
    - name: ensemble-container
      image: docker.io/stasbochok-opens-ml/app-fastapi:latest
      env:
      - name: WANDB_API_KEY
        valueFrom:
          secretKeyRef:
            name: wandb
            key: WANDB_API_KEY
      resources:
        limits:
          memory: 2Gi
          cpu: 1
    batcher:
      maxBatchSize: 32
      maxLatency: 200
      timeout: 60
    inferenceGraph:
      steps:
      - name: model-1
        predictor:
          serviceName: bone-fracture-model-1
      - name: model-2
        predictor:
          serviceName: bone-fracture-model-2
      - name: ensemble
        aggregator:
          type: "mean"
