apiVersion: batch/v1
kind: Job
metadata:
  name: job-module1
spec:
  parallelism: 2
  template:
    spec:
      restartPolicy: Never
      containers: 
        - name: job-module1
          image: docker.io/stasbochok/simple-server:module1
