jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List directory contents
        run: |
          ls -la module1

      - name: Run app.py
        run: | 
          python module1/app.py
