---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-gradio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-gradio
  template:
    metadata:
      labels:
        app: app-gradio
    spec:
      containers:
        - name: app-streamlit
          image: docker.io/stasbochok/app-gradio:latest:latest
          env:
          - name: WANDB_API_KEY
            valueFrom:
              secretKeyRef:
                name: wandb
                key: WANDB_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: app-gradio
  labels:
    app: app-gradio
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: app-gradio
