name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install io numpy unittest tensorflow fastapi pillow wandb uvicorn python-multipart

    - name: Run tests
      run: |
        python -m unittest module5/HW9/api-model/test_api_model.py

    - name: Build Docker image
      run: |
        docker build -t api_model:latest .

    - name: Run FastAPI app in a container
      run: |
        docker run -d -p 8000:8000 api_model:latest
