name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install gradio wandb tensorflow numpy pillow 

      - name: Run tests
        run: |
         python -m unittest module5/HW9/gradio/test_grad.py

      - name: Run tests
        run: |
          export PYTHONPATH=$(pwd)/module5/HW9/streamlit
          python -m unittest discover -s module5/HW9/gradio -p 'test_grad.py'

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install gradio wandb tensorflow numpy pillow

      - name: Run Gradio app (for deployment verification)
        run: |
          nohup python module5/HW9/gradio/grad.py &
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

      - name: Check Gradio app
        run: |
          curl -sS http://localhost:7860
        continue-on-error: true
