name: Module1

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    paths:
      - 'module1/**'

jobs:

  k8s-test-deployment-action:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0

      - name: Checkout 
        uses: actions/checkout@v4

      - name: Deploy application
        run: |
          kubectl create -f module1/k8s-resources/deployment-app-web.yaml

      - name: Print pods
        run: |
          sleep 5 && kubectl get pod -A

      - name: Wait for deployment
        run: |
          kubectl wait --for=condition=available --timeout=90s deployment/deployments-module1

      - name: Print pods again
        run: |
          sleep 5 && kubectl get pod -A
