name: Module 1

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/module1:${{ github.sha }} .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/module1:${{ github.sha }}

    - name: Run container
      run: docker run --rm -d -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/module1:${{ github.sha }}

    - name: Test container
      run: curl --fail http://localhost:8000

    - name: Stop container
      run: docker stop $(docker ps -q --filter ancestor=${{ secrets.DOCKER_USERNAME }}/module1:${{ github.sha }})

    - name: Logout from Docker Hub
      run: docker logout
