name: Module 1 DOCKER

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    paths:
      - 'module1/**'
      
env:
  IMAGE_ML_APP: app


jobs:
  ci-test-bash-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Test echo
        run: |
          echo 'test'

      - name: Test ls
        run: |
          ls -all .

  app-ml-docker-but-with-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login docker.io -u stasbochok --password-stdin


      - name: Build 
        run: |
          docker build --tag docker.io/stasbochok/simple-server:module1 ./module1                         

      - name: Push 
        run: |
          docker push docker.io/stasbochok/simple-server:module1

      - name: Run ok
        run: |
          docker run --rm --name app-run docker.io/stasbochok/simple-server:module1


  app-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
    
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: docker.io/stasbochok/app
                  
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./module1
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

