name: CI Pipeline 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install streamlit wandb tensorflow numpy pillow


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install streamlit wandb tensorflow numpy pillow

      - name: Run Streamlit app (for deployment verification)
        run: |
          nohup streamlit run module5/HW9/streamlit/stream.py &
          sleep 10
          curl -sS http://localhost:8501 || true
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        continue-on-error: true

      - name: Kill Streamlit app
        run: |
          pkill -f streamlit
        continue-on-error: true
